version: "3.8"

services:
  backend:
    build:
      context: .
      network: host
      args:
        VITE_LINE_CLIENT_ID: ${VITE_LINE_CLIENT_ID}
        VITE_REDIRECT_URI: ${VITE_REDIRECT_URI}
    ports:
      - "3000:3000"
    volumes:
      - ./database:/app/backend/database
      - ./.env.backend:/app/backend/.env:ro
    env_file:
      - .env