version: "3.8"

services:
  backend:
    build:
      context: .
      network: host
      args:
        VITE_LINE_CLIENT_ID: ${VITE_LINE_CLIENT_ID}
        VITE_REDIRECT_URI: ${VITE_REDIRECT_URI}
    ports:
      - "80:3000"
      - "443:8443"
    volumes:
      - ./database:/app/backend/database
      - ./logs:/app/backend/logs
      - ./certs:/app/backend/certs
      - ./.env.backend:/app/backend/.env:ro
    env_file:
      - .env